### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by FrankBrullo** [britecharts/britecharts-react#139]
It seems that the library doesn't have the Typescript types defined.
I tried to do **npm i @types/britecharts-react** but the module doesn't exist.

I used `react-scripts-ts` to create my react test project.

Below the TypeScript error I get from the compiler when I import the library:

_Could not find a declaration file for module 'britecharts-react'. 'test-app/node_modules/britecharts-react/dist/britecharts-react.min.js' implicitly has an 'any' type.
  Try `npm install @types/britecharts-react` if it exists or add a new declaration (.d.ts) file containing `declare module 'britecharts-react';`_

**Comment by Golodhros** [comment]
Hi @FrankBrullo, thanks for opening this issue.

Yes, we don't have TS types. Several people talked about it in https://github.com/eventbrite/britecharts/issues/223, but never came out of it yet.

We are open to PRs though.

**Comment by FrankBrullo** [comment]
Ok, I will do and let you know when the PR is ready.
Also, while I am looking at the Donut I am not seeing implemented **customMouseMove** and more importantly **customClick**.
Any idea why?
How can I get the click event in React if they aren't defined as props?

Thanks.

**Comment by Golodhros** [comment]
That would be awesome @FrankBrullo!! Thanks a lot for doing this!!

True, those handlers are not set, but they should. We would need to add them there as proptypes and they should be ready to use!

**Comment by FrankBrullo** [comment]
@Golodhros That would be great!
Do you have an ETA on when it will be fixed?
I need to include those events in my Typescript types for the Pie Chart before sending the PR to you.

Thanks,
Frank

**Comment by Golodhros** [comment]
I will try to go over it this weekend, but until we fix the release issue(hopefully next week) we won't be able to publish it.

**Comment by FrankBrullo** [comment]
Let me know when you push your changes on Git so I can update my fork.
I hope to deliver the Typescript changes before your release so we will have everything in one shot.

**Comment by miglesiasEB** [comment]
Hi @FrankBrullo, the handlers are ready and the release pipeline is working again!

**Comment by dupski** [comment]
+1 for TS support. Give me a shout if you need any assistance @FrankBrullo :)

**Comment by FrankBrullo** [comment]
Hi @miglesiasEB sorry for the radio silence but I got some issues to continue working on the PR.
Now I have sorted out everything and I have restarted.
Is there a way I can get an invite to join your slack channel so I can ask you a couple of questions I have?

@dupski Thank you for the offer I will definitely take it! :) I will send you a preliminary PR for you to review because I am not much familiar with most of the chart and probably I will not have time to check all of them once I am done with the TS definitions.

**Comment by dupski** [comment]
Same here regarding familiarity @FrankBrullo as I'm only just starting with this library but happy to take a look and give it a test :)

**Comment by miglesiasEB** [comment]
Sounds good!

We have a channel in the official [d3 slack](https://d3js.slack.com/). Join us there @FrankBrullo !

**Comment by isaiahtaylor** [comment]
Any motion on this?

**Comment by Golodhros** [comment]
Not really, a lot of people offered to add the types but nobody actually did!

**Comment by ImADrafter** [comment]
I think It would be interesting to have [this one](https://github.com/britecharts/britecharts/pull/868), since some types can be reused. Anyway, we can start typing the props and the whole config before that gets merged. May I work on this ? :D

**Comment by Golodhros** [comment]
Hi @ImADrafter!
I hope we could reuse the types between Britecharts and Britecharts-react, and use them to keep track of how complete are the Britechart React apis.

In my mind, the future should be a monorepo for britecharts, with @britecharts/core, @britecharts/react, @britecharts/types, @britecharts/angular and so on.

If you have time to work on this stuff, I would actually love to get some help on making https://github.com/britecharts/britecharts/pull/868 work.
