### ISSUE TITLE
Support Locale in Bar Chart

### ISSUE THREAD

**Issue by brandtOSS** [britecharts/britecharts-react#175]
The Britecharts library introduced options to set the locale for the bar chart.
This enables overriding the standard number formatting and for example use different decimal separators and/or currency symbols in the axis labels and the bars labels.

## Expected Behavior
Being able to change the locale, e.g. allow GBP or EUR sign be used for number formatting.

## Difference from Current Behavior
No locale setting(s) available in the bar chart component.

## Possible Implementation
Introduce a new property to pass the locale information as an object into Britecharts.

## Context
Format monetary values e.g. as "1.3k Euro" or "1325 €" in the bar labels.

## Link to relevant commit in Britecharts repo:
[Dec 12, 2019 - 96c665753fd31f265f31a095f6fea95200fdaaa2](https://github.com/britecharts/britecharts/commit/96c665753fd31f265f31a095f6fea95200fdaaa2)

**Comment by Golodhros** [comment]
Included on the RC1: https://github.com/britecharts/britecharts-react/commits/release/1.0.0-rc1
