### ISSUE TITLE
Broken and unclear documentation 

### ISSUE THREAD

**Issue by zedtux** [britecharts/britecharts-react#191]
## Expected Behavior
I'm trying to get a line chart working but it's quite hard since [the Line documentation examples are broken](https://britecharts.github.io/britecharts-react/#line) and quite unclear because, for instance, the first example code look like this:

```javascript
const lineData = require('./lineChart.fixtures').default;
    const ResponsiveContainer = require('../helpers/responsiveContainer.js').default;
    const margin = {
        top: 60,
        right: 30,
        bottom: 60,
        left: 70,
    };

    const renderLine = (props) => (
        <ResponsiveContainer
            render={
                ({width}) =>
                    <Line
                        margin={margin}
                        lineCurve="basis"
                        width={width}
                        {...props}
                    />
            }
        />
    );

    <Tooltip
        data={lineData.oneSet()}
        render={renderLine}
        topicLabel="topics"
        title="Tooltip Title"
    />
```
The import of the `<Line>` component seem to be missing?

## Current Behavior

After searching a lot, I got a working chart, and I wanted to changed the `axisTimeCombinations` prop. I see there _should_ be some constants to be used (here too, the documentation has a formatting issue on the constant names):

> MINUTE_HOUR, HOUR_DAY, DAY_MONTH, MONTH_YEAR

But I can't find them in this package so I tried to use `0` and then `1`, hoping to find a good one by any luck but then it fails with the following error:

```
Uncaught TypeError: t[e] is not a function
    React 11
    unstable_runWithPriority scheduler.development.js:661
    React 5
    unstable_runWithPriority scheduler.development.js:661
    React 4
    Redux 7
    fetchOneResponseTimes actions.js:21
britecharts-react.min.js:49
    o React
    o self-hosted:954
    forEach self-hosted:225
    React 10
    commitRootImpl self-hosted:954
    unstable_runWithPriority scheduler.development.js:661
    React 4
    performSyncWorkOnRoot self-hosted:897
    flushSyncCallbackQueueImpl React
    unstable_runWithPriority scheduler.development.js:661
    React 4
    Redux 3
    handleChangeWrapper self-hosted:850
```

The package JavaScript seems to be minified, so it's unreadable :man_shrugging:.

Here is my code so far:

```jsx
<ResponsiveContainer
              render={
                ({ width }) => (
                  <Line
                    axisTimeCombinations={2}
                    data={{ data: oneResponseTimes }}
                    lineCurve="basis"
                    margin={{
                      top: 60,
                      right: 30,
                      bottom: 60,
                      left: 70
                    }}
                    height={200}
                    width={width}
                  />
                )
              }
            />
```

BTW I can't get the `<ResponsiveContainer>` component to update the `width`.

## Your Environment
* Britecharts-React version used: latest (0.5.4)
* Browser Name and version: Firefox 78.5.0esr (64-bit)
* Operating System and version: Linux Debian Buster

**Comment by Golodhros** [comment]
Thanks for the issue @zedtux! 
Sorry for that, I will try to jump into this during the weekend!

**Comment by Golodhros** [comment]
This fixes the demo: https://github.com/britecharts/britecharts-react/pull/192

**Comment by Golodhros** [comment]
You are right about the axisTimeCombinations, that should be provided along with the chart component. I will fix that soon.

For now, you can reference this file: **https://github.com/Golodhros/britecharts/blob/6cc31390f7acbe21faafbf30baeeb5921c4c3810/src/charts/helpers/constants.js#L8**

**Comment by Golodhros** [comment]
This should fix it: https://github.com/britecharts/britecharts-react/pull/193

**Comment by zedtux** [comment]
Just to let you know: I've switched to another library, but it's cool you're fixing all that things. Will see in a next project if this lib is strong enough 😉

**Comment by Golodhros** [comment]
> Just to let you know: I've switched to another library, but it's cool you're fixing all that things. Will see in a next project if this lib is strong enough 😉

Totally understand!
We have left aside Britecharts React for too long while we prepare Britecharts V3. Hopefully you will get all the new goodness when you are back to check!

**Comment by marcelovani** [comment]
composer.json needs to be updated to use the latest tag https://github.com/britecharts/britecharts-react/releases/tag/0.6.3

**Comment by Golodhros** [comment]
> package.json needs to be updated to use the latest tag https://github.com/britecharts/britecharts-react/releases/tag/0.6.3

Not sure if I understand, it seems the package.json version is 0.6.3

**Comment by marcelovani** [comment]
Sorry, I was meant to paste this url https://github.com/britecharts/britecharts-react-test-project/blob/master/package.json
The test project is still broken on master

**Comment by Golodhros** [comment]
> Sorry, I was meant to paste this url https://github.com/britecharts/britecharts-react-test-project/blob/master/package.json
> The test project is still broken on master

Ah, thanks for the heads up!!
