### ISSUE TITLE
customClick method is not working

### ISSUE THREAD

**Issue by marcelovani** [britecharts/britecharts-react#201]
The customClick method is broken.

I tracked this comment https://github.com/britecharts/britecharts-react/issues/139#issuecomment-437157806 where they talk about it, it then gets implemented, but probably never tested.

## Expected Behavior
When I use customClick in my React component, it should detect mouse clicks

## Current Behavior
Javascript error: Uncaught Error: Method not supported by Britechart: customClick

## Possible Solution
Add missing item on charts/constants.js

## Steps to Reproduce
Create a component with customClick and the relevant function
    <Donut
      data={Data}
      isAnimated={true}
      width={containerWidth}
      height={containerHeight}
      customClick={handleMouseClick.bind(this)}
    />

## Screenshots (if appropriate)
![Screenshot 2021-01-16 at 09 06 09](https://user-images.githubusercontent.com/2162363/104807882-29296d80-57da-11eb-8681-91673d8b6593.jpg)

**Comment by marcelovani** [comment]
PR here https://github.com/britecharts/britecharts-react/pull/202

**Comment by marcelovani** [comment]
Thank you for merging the pr. Shall I close the issue now or we close after you make a new release?

**Comment by Golodhros** [comment]
Closing now, fix in its way on v0.6.4
